name: 真实爬虫更新
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: 安装必要插件
        run: pip install requests
      - name: 执行真实抓取
        run: python crawl.py
      - name: 提交并推送到网站
        run: |
          git config --global user.name 'Real-News-Bot'
          git config --global user.email 'bot@github.com'
          git add .
          git commit -m "今日真实新闻已送达"
          git push
